embeddings {
  tensor_name: "customer:07282"
  metadata_path: "07282/customer/metadata.tsv"
  tensor_path: "07282/customer/tensors.tsv"
}
embeddings {
  tensor_name: "line:07282"
  metadata_path: "07282/line/metadata.tsv"
  tensor_path: "07282/line/tensors.tsv"
}
