embeddings {
  tensor_name: "customer:09780"
  metadata_path: "09780/customer/metadata.tsv"
  tensor_path: "09780/customer/tensors.tsv"
}
embeddings {
  tensor_name: "line:09780"
  metadata_path: "09780/line/metadata.tsv"
  tensor_path: "09780/line/tensors.tsv"
}
