embeddings {
  tensor_name: "customer:09146"
  metadata_path: "09146/customer/metadata.tsv"
  tensor_path: "09146/customer/tensors.tsv"
}
embeddings {
  tensor_name: "line:09146"
  metadata_path: "09146/line/metadata.tsv"
  tensor_path: "09146/line/tensors.tsv"
}
