embeddings {
  tensor_name: "customer:10464"
  metadata_path: "10464/customer/metadata.tsv"
  tensor_path: "10464/customer/tensors.tsv"
}
embeddings {
  tensor_name: "line:10464"
  metadata_path: "10464/line/metadata.tsv"
  tensor_path: "10464/line/tensors.tsv"
}
