embeddings {
  tensor_name: "customer:05216"
  metadata_path: "05216/customer/metadata.tsv"
  tensor_path: "05216/customer/tensors.tsv"
}
embeddings {
  tensor_name: "line:05216"
  metadata_path: "05216/line/metadata.tsv"
  tensor_path: "05216/line/tensors.tsv"
}
