embeddings {
  tensor_name: "customer:06520"
  metadata_path: "06520/customer/metadata.tsv"
  tensor_path: "06520/customer/tensors.tsv"
}
embeddings {
  tensor_name: "line:06520"
  metadata_path: "06520/line/metadata.tsv"
  tensor_path: "06520/line/tensors.tsv"
}
