embeddings {
  tensor_name: "customer:01863"
  metadata_path: "01863/customer/metadata.tsv"
  tensor_path: "01863/customer/tensors.tsv"
}
embeddings {
  tensor_name: "line:01863"
  metadata_path: "01863/line/metadata.tsv"
  tensor_path: "01863/line/tensors.tsv"
}
